/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_bfh_android_zeadl_I2C */

#ifndef _Included_ch_bfh_android_zeadl_I2C
#define _Included_ch_bfh_android_zeadl_I2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_bfh_android_zeadl_I2C
 * Method:    open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ch_bfh_android_zeadl_I2C_open
  (JNIEnv *, jobject);

/*
 * Class:     ch_bfh_android_zeadl_I2C
 * Method:    read
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_ch_bfh_android_zeadl_I2C_read
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     ch_bfh_android_zeadl_I2C
 * Method:    write
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_ch_bfh_android_zeadl_I2C_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     ch_bfh_android_zeadl_I2C
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_bfh_android_zeadl_I2C_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
